POST http://localhost:8090/v2/student
Content-Type: application/json

{
 "studentId" :  1,
 "fullName" : "Jesus Carlos Antonio Rocha Vedia"
}
###

PUT http://localhost:8090/v2/student
Content-Type: application/json

{
  "studentId" :  1,
  "fullName" : "Lucas Paz"
}
###

GET http://localhost:8090/v2/student/?studentId=30
Content-Type: application/json

###

DELETE http://localhost:8090/v2/student/?studentId=30
Content-Type: application/json

###